# workflow name
name: Build and deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3

      - name: install emacs
        run: |
          apt update
          apt upgrade
          apt install emacs

      # Runs a set of commands using the runners shell
      - name: build site
        run: |
          echo "Building site"
          bash build.sh
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: .
