# workflow name
name: Build and deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
      
      - name: setup node.js env
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16
        
#      - name: install node
#        run: |
#          cd ~
#          sudo curl -s https://deb.nodesource.com/setup_16.x | sudo bash
#          sudo apt update
#          sudo apt upgrade -y
#          sudo apt install -y --no-install-recommends nodejs
          
      - name: change default npm directory
        run: |
          sudo mkdir ~/npm-global
          sudo npm config set prefix '~/npm-global'
          sudo echo 'PATH=~/npm-global/bin:$PATH' > ~/.profile
          source ~/.profile
          
      - name: configure global babel support (es6) with npm
        run: |
          sudo npm i -g babel-cli babel-preset-es2015 babel-preset-stage-0 babel-preset-stage-1 babel-preset-stage-2 babel-preset-stage-3 babel-preset-react
          sudo ln -s ~/npm-global/babel-cli/bin/babel-cli/bin/babel-node.js /usr/local/bin/org-babel-node
          
      - name: check directory
        run: |
          ls ~/npm-global
          ls ~/npm-global/babel-cli

      - name: configure global react support with npm
        run: sudo npm i -g react react-dom react-router-dom
        
      - name: configure global html prettifier
        run: sudo npm i -g simply-beautiful

      - name: install emacs
        run: sudo apt install emacs -y

      # Runs a set of commands using the runners shell
      - name: build site
        run: |
          echo "Building site"
          bash build.sh
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: .
